services:
  backend:
    build: ./backend
    container_name: trip_backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env

    networks:
      - trip_net

  frontend:
    build: ./frontend
    container_name: trip_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    networks:
      - trip_net

networks:
  trip_net:
    driver: bridge