services:
  backend:
    build: ./Backend
    container_name: trip_backend

    ports:
      - "5000:5000"

    volumes:
      - ./Backend:/app
      - /app/node_modules

    env_file:
      - ./Backend/.env

    networks:
      - trip_net

  frontend:
    build: ./Frontend
    container_name: trip_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./Frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    networks:
      - trip_net

networks:
  trip_net:
    driver: bridge