/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirefliesRouteImport } from './routes/fireflies'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RecordRouteImport } from './routes/record'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiInterpretRouteImport } from './routes/api/interpret'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTtsStreamRouteImport } from './routes/api/tts-stream'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirefliesRoute = FirefliesRouteImport.update({
  id: '/fireflies',
  path: '/fireflies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterpretRoute = ApiInterpretRouteImport.update({
  id: '/api/interpret',
  path: '/api/interpret',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/api/tts-stream',
  path: '/api/tts-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fireflies': typeof FirefliesRoute
  '/library': typeof LibraryRouteWithChildren
  '/mcp': typeof McpRoute
  '/record': typeof RecordRoute
  '/upload': typeof UploadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/interpret': typeof ApiInterpretRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/library/$id': typeof LibraryIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fireflies': typeof FirefliesRoute
  '/library': typeof LibraryRouteWithChildren
  '/mcp': typeof McpRoute
  '/record': typeof RecordRoute
  '/upload': typeof UploadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/interpret': typeof ApiInterpretRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/library/$id': typeof LibraryIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fireflies': typeof FirefliesRoute
  '/library': typeof LibraryRouteWithChildren
  '/mcp': typeof McpRoute
  '/record': typeof RecordRoute
  '/upload': typeof UploadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/interpret': typeof ApiInterpretRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/library/$id': typeof LibraryIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fireflies'
    | '/library'
    | '/mcp'
    | '/record'
    | '/upload'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/interpret'
    | '/api/transcribe'
    | '/api/tts-stream'
    | '/library/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fireflies'
    | '/library'
    | '/mcp'
    | '/record'
    | '/upload'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/interpret'
    | '/api/transcribe'
    | '/api/tts-stream'
    | '/library/$id'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/fireflies'
    | '/library'
    | '/mcp'
    | '/record'
    | '/upload'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/interpret'
    | '/api/transcribe'
    | '/api/tts-stream'
    | '/library/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirefliesRoute: typeof FirefliesRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  McpRoute: typeof McpRoute
  RecordRoute: typeof RecordRoute
  UploadRoute: typeof UploadRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiInterpretRoute: typeof ApiInterpretRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fireflies': {
      id: '/fireflies'
      path: '/fireflies'
      fullPath: '/fireflies'
      preLoaderRoute: typeof FirefliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interpret': {
      id: '/api/interpret'
      path: '/api/interpret'
      fullPath: '/api/interpret'
      preLoaderRoute: typeof ApiInterpretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-stream': {
      id: '/api/tts-stream'
      path: '/api/tts-stream'
      fullPath: '/api/tts-stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirefliesRoute: FirefliesRoute,
  LibraryRoute: LibraryRouteWithChildren,
  McpRoute: McpRoute,
  RecordRoute: RecordRoute,
  UploadRoute: UploadRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiInterpretRoute: ApiInterpretRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsStreamRoute: ApiTtsStreamRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
